### ISSUE TITLE
Crashes when clicking on profile 

### ISSUE THREAD

**Issue by victorious96** [LemaMichael/Unicorn#2]
I tried the Version 9.9.6 and 10.0.0 and it has this issue for me. Anyone else?

**Comment by LemaMichael** [comment]
I was able to reproduce this issue and added it as a High Priority bug.

**Comment by victorious96** [comment]
It seemed to work if I uninstall the tweak and remove the app and reinstall. But later on (after using it for  weeks). The bug happens again. Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by LemaMichael** [comment]
The issue seems to be the draft videos.  When you deleted the app, you also deleted your draft videos which seemed to solve the issue. I will be pushing a new update with a fix soon.
