### ISSUE TITLE
Sideloading (No Jailbreak)

### ISSUE THREAD

**Issue by LemaMichael** [LemaMichael/Unicorn#3]
**Is your feature request related to a problem? Please describe.**
Create an IPA file for non-jailbroken users. 

**Additional context**
Requested by @domlast425

**Comment by LemaMichael** [comment]
The app is available on [Ignition](https://ignition.fun) and other similiar services.

**Comment by ghost** [comment]
@LemaMichael could you add a duplicate version? ( one with different id that the original one)
