### ISSUE TITLE
Request for updating the github repo

### ISSUE THREAD

**Issue by rabe398** [LemaMichael/Unicorn#5]
**Is your feature request related to a problem? Please describe.**
I’m currently trying to fork the project so I can create a feature that would make my life easier on tiktok, but I need you to update the github repo so i can work on the latest version of the code.

**Describe the solution you'd like**
Updating the tweak’s code on github

**Comment by LemaMichael** [comment]
You can fork the project and submit a pull request. Depending on the feature you create, I can add it to  v2.3 and give you credit.

**Comment by rabe398** [comment]
Can you update the github code so it would match v2.2?

**Comment by LemaMichael** [comment]
No, there are certain features of the tweak that can abuse the TikTok API.

**Comment by rabe398** [comment]
The only reason i want to fork it is to impement my own version of media vault, my camera roll album is a mess because of tik tok.
Why did u open source the project if you aren’t planning to keep it updated?
@LemaMichael
