### ISSUE TITLE
Freezes when I click on user's page

### ISSUE THREAD

**Issue by alacielx** [LemaMichael/Unicorn#9]
#**Describe the bug**
When I go to anyone's page it freezes and I can't click anything so I have to close the app

**To Reproduce**
1. Click someone's profile
2. It freezes

**Smartphone:**
 - Device: iPhone 7
 - OS: iOS 13.3
 - TikTok Version v15.3.0

**Comment by LemaMichael** [comment]
The bug is fixed in version 4.0
